# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    ### Controllers available
    rb1_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true

### Properties of the controllers that we will use and definition of joints to use ###
rb1_base_controller:
  ros__parameters:
    
    publish_rate: 50.0 # Has to be a double otherwise errors are encountered

    base_frame_id: rb1_robot/robot_base_footprint

    left_wheel_names: ['rb1_robot/robot_left_wheel_joint']
    right_wheel_names: ['rb1_robot/robot_right_wheel_joint']
    wheel_separation: 0.436
    wheel_radius: 0.076

    # Obtained from https://wiki.ros.org/diff_drive_controller
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0] 

    # Whether the input has a time stamp or not
    use_stamped_vel: false

    # Odometry fused with IMU is published by robot_localization, so no need to publish a TF
    # based on encoders alone (https://wiki.ros.org/diff_drive_controller)
    enable_odom_tf: false

